config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  resources :articles
  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories 
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories 
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
                      uniqueness: { case_sensitive: false}, 
                      length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                      uniqueness: { case_sensitive: false}, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def required_user
    if !logged_in?
      flash[:alert] = "You must be logged int to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :required_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    #byebug for debugging purposes
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit your own articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was succesfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category was succesfully updated"
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can manage existing categories"
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update ,:destroy]
  before_action :required_user, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /users or /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/1 or /users/1.json
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    respond_to do |format|
      format.html { redirect_to articles_path, notice: "User and their associated articles were successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own profile"
        redirect_to @user
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Created</th>
      <th>User</th>
      <th>Categories<th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= time_ago_in_words(article.created_at) %></td>   
        <% if article.user %>
          <td><%= link_to article.user.username, user_path(article.user) %></td>
        <% end %>
        <% if article.categories.any? %>
          <td>
            <%= render article.categories %>
          <td>
        <%else%>
          <td><p>None</p><td>
        <%end%>   
        <td><%= link_to 'Show', article %></td>
        <% if logged_in? && (article.user == current_user || current_user.admin?)%>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?"} %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%if @article.errors.any? %>
  <h2>The following errors prevented the article from being updated</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p> 
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p> 
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>

<p> 
  <%= f.label :category %>
  <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list bellow (can be empty)"}, { multiple: true })%>
</p>

<p> 
  <%= f.submit %>
</p>

<%end%>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/articles/index.html.erb
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<h1>Articles</h1>


<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<br>
<%= render 'article' %>

<p>
  <% if logged_in? %>
    <td><%= link_to 'Create New Article', new_article_path %></td>
  <% end %>
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user.username if @article.user %>
</p>

<% if @article.categories.any? %>
  <p>
    <strong>Categories</strong>
    <%= render @article.categories %>
  </p>
<%end%>

<p>
  <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
    <%= link_to 'Edit', edit_article_path(@article) %>
    <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %>
  <% end %>
  <%= render 'sessions/login_footer' %>
</p>

app/views/categories/_category.html.erb
<p class="flickr_pagination">
  <%= link_to category.name, category_path(category) %>
</p>

app/views/categories/_form.html.erb
<%if @category.errors.any? %>
  <h2>The following errors prevented the article from being updated</h2>
  <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @category, local: true) do |f| %>

<p> 
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p> 
  <%= f.submit %>
</p>

<%end%>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/categories/index.html.erb
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<h1>Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Articles</th>
      <th>Created</th>
      <th>Edited</th>
      <th colspan="1">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= category.articles.count %></td>
        <td><%= time_ago_in_words(category.created_at) %></td>
        <td><%= time_ago_in_words(category.updated_at) %></td>
        <td><%= link_to 'Show', category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <% if logged_in? && current_user.admin?%>
    <td><%= link_to 'Create New Category', new_category_path %></td>
  <% end %>
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', user: @user %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/categories/show.html.erb
<h1>Showing Category Details</h1>
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<p><h2>
  <strong>Title:</strong>
  <%= @category.name %>
  <h2>
</p>

<h3>Articles</h3>
<br>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<br>

<%= render 'articles/article' %>

<p>
  <% if logged_in? && current_user.admin %>
    <%= link_to 'Edit category', edit_category_path(@category) %>
  <%end%>
  <%= render 'sessions/login_footer' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Alpha Blog6 Home</h1>

<%= render 'sessions/login_footer' %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/users/index.html.erb
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<h1>Users</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <% if logged_in? %>
        <th>Email</th>
      <%end%>
      <th>Articles</th>
      <th>Joined</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <% if logged_in? %>
          <td><%= user.email %></td>
        <%end%>
        <td><%= user.articles.count %></td>
        <td><%= time_ago_in_words(user.created_at) %></td>
        <td><%= link_to 'Show', user %></td>
        <% if logged_in? %>
          <% if user == current_user %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <% end %>
          <% if current_user.admin?  %>
            <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<p>
  <%= render 'sessions/login_footer' %>
</p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<p> 
  <td><%= render 'sessions/login_footer' %></td>
</p>

app/views/users/show.html.erb
<p id="notice" style="color:green;"><%= notice %></p>
<p id="alert" style="color:red;"><%= alert %></p>

<h1><%= @user.username %>'s profile</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<% if logged_in? %>
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
<%end%>
<h2>Articles</h2>
<br>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<br>

<%= render 'articles/article' %>

<p>
  <% if logged_in? && @user == current_user %>
    <%= link_to 'Edit user\'s profile', edit_user_path(@user) %>
  <%end%>
  <%= render 'sessions/login_footer' %>
</p>